# Generated by Django 3.0.3 on 2020-02-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200221_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.ForeignKey(blank=True, default='todo', on_delete=django.db.models.deletion.SET_DEFAULT, to='user.Progress'),
        ),
    ]
