# Generated by Django 3.0.3 on 2020-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200221_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='tasks',
            field=models.ManyToManyField(related_name='watch_tasks', to='user.Task'),
        ),
    ]
