# Generated by Django 3.0.3 on 2020-02-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200221_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Role'),
        ),
    ]
