# Generated by Django 3.0.3 on 2020-02-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_task_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Progress'),
        ),
    ]
